### ISSUE TITLE
Java21: nio.Path resolveSibling return value should probably be non-null

### ISSUE THREAD

**Issue by blablubbabc** [vegardit/no-npe#257]
https://github.com/vegardit/no-npe/blob/main/libs/eea-java-21/src/main/resources/java/nio/file/Path.eea#L65
I.e. should be
```
class java/nio/file/Path
resolveSibling
 (Ljava/lang/String;)Ljava/nio/file/Path;
 (L1java/lang/String;)L1java/nio/file/Path;
resolveSibling
 (Ljava/nio/file/Path;)Ljava/nio/file/Path;
 (L1java/nio/file/Path;)L1java/nio/file/Path;
```
---
Also, the `PrimitiveIterator` parameters should by typed as always NonNull, so that one can cast for example `IntStream::iterator` (returns `PrimitiveIterator.OfInt`) to `Iterable<@NonNull Integer>`.
I.e.
```
class java/util/PrimitiveIterator
 <T:Ljava/lang/Object;T_CONS:Ljava/lang/Object;>
 <1T:Ljava/lang/Object;T_CONS:Ljava/lang/Object;>
```
Example:
```
// NonNullByDefault
	private static Iterable<Integer> asIterable(IntStream stream) {
		// Error: "Null type safety at method return type: Method descriptor
		// Iterable<Integer>.iterator() promises '@NonNull Iterator<@NonNull Integer>' but
		// referenced method provides 'PrimitiveIterator.@NonNull OfInt'"
		return stream::iterator;
	}
```
---
Also, `AbstractStringBuilder#substring` should be non-null
```
class java/lang/AbstractStringBuilder
substring
 (I)Ljava/lang/String;
 (I)L1java/lang/String;
substring
 (II)Ljava/lang/String;
 (II)L1java/lang/String;
```

**Comment by sebthom** [comment]
Thanks for reporting. I adjusted Path and PrimitiveIterator. 

AbstractStringBuilder is only package visible. EEAs are currently not maintained/generated for private and package visible classes to reduce the final jar sizes. AbstractStringBuilder  only has two subclasses StringBuilder and StringBuffer, for both the EEAs are specified for the substring methods.

**Comment by blablubbabc** [comment]
Java21 StringBuilder doesn't seem to contain a definition for `subtring`: https://github.com/vegardit/no-npe/blob/main/libs/eea-java-21/src/main/resources/java/lang/StringBuilder.eea

**Comment by sebthom** [comment]
good point, I now changed the EEA generator to also create an EEA file for the AbstractStringBuilder class. That should solve this issue.

**Comment by blablubbabc** [comment]
Thanks!
