### ISSUE TITLE
Document how this generates/updates EEAs - from what?

### ISSUE THREAD

**Issue by vorburger** [vegardit/no-npe#268]
@sebthom 👋 Hi!

I've (finally, never had any time before) had a slightly closer look at this repo only just today. The README says:

> update/regenerate all EEA files

and 

> Creation of this project was inspired by https://github.com/lastnpe/eclipse-null-eea-augments/ but a different approach in generating/packaging/validating of EEA files/archives has been taken.

First of all, Thank You for the ACK.

I was trying to better understand, and then perhaps contribute a PR here to share that understanding, of how this actually works... but I haven't really figured out yet what this reads as input source to generate EEAs from? (And I admit that I haven't looked at its source code to just figure it out.)

**Comment by sebthom** [comment]
The EEA Generator can scan classes using ClassGraph and output EEA files containing signatures of all methods and fields. It contains some heuristic to mark fields nullable/non-null either based on different annotations (see https://github.com/vegardit/no-npe/blob/549ccd9f1d0904315eb2d528426b42fbfbb71c48/eea-generator/src/main/java/com/vegardit/no_npe/eea_generator/internal/ClassGraphUtils.java#L24-L80) or if methods/fields follow certain well known conventions ( see https://github.com/vegardit/no-npe/blob/549ccd9f1d0904315eb2d528426b42fbfbb71c48/eea-generator/src/main/java/com/vegardit/no_npe/eea_generator/EEAGenerator.java#L213-L318). 

The idea now is that when a library is updated, e.g. classes are added/removed etc. You rerun the Generator which scans the classes and also reads the EEAs that were generated (and potentially modified) before and then re-applies those EEAs before it writes the updated EEA files.

I hope that makes sense :-)

**Comment by vorburger** [comment]
> then perhaps contribute a PR here to share that understanding

Or not here anymore, but over on https://github.com/lastnpe/eclipse-null-eea-augments, after #168 is merged...

**Comment by vorburger** [comment]
> Or not here anymore, but over on https://github.com/lastnpe/eclipse-null-eea-augments, after https://github.com/lastnpe/eclipse-null-eea-augments/pull/168 is merged...

At least partially done in https://github.com/lastnpe/eclipse-null-eea-augments/pull/168/commits/77a4946a9ea1346c6a219244603034822367af85 already, it seems.

**Comment by sebthom** [comment]
Let's discuss things in the LastNPE repo.
