### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by llgcode** [vegardit/no-npe#79]
Hello,
I don't use maven to build my project but wanted to use you project.
I don't find any binaries under this https://search.maven.org/search?q=g:com.vegardit.no-npe that is currently published in your README.

Would it be possible to provide a binary ?

**Comment by sebthom** [comment]
jars of a 1.0.0-SNAPSHOT pre-releases are available under https://raw.githubusercontent.com/vegardit/no-npe/mvn-snapshots-repo, which you can also use with gradle in case that is your build system.

you can also manually download the jars here https://github.com/vegardit/no-npe/tree/mvn-snapshots-repo/com/vegardit/no-npe

**Comment by llgcode** [comment]
Thanks for your help, it's ok on my side

**Comment by sebthom** [comment]
@llgcode the jars are now also available on Maven central, see https://search.maven.org/search?q=g%3Acom.vegardit.no-npe
